Rails:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Metrics/LineLength:
  Max: 100
